<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>23&nbsp; The inferential machinery: test statistics, z/t/F, and degrees of freedom – Understanding and analyzing social and behavioral data</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./24-decisions-errors-power-sesoi.html" rel="next">
<link href="./22-pvalues-fisher-neyman-pearson.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d43978d6016da14795327a5bd638d710.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-d685995fa19fd69abfd2845f2861e92b.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-d43978d6016da14795327a5bd638d710.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/custom.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./21-why-inference.html">Section 4: Statistical Inference</a></li><li class="breadcrumb-item"><a href="./23-test-statistics-and-df.html"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">The inferential machinery: test statistics, z/t/F, and degrees of freedom</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Understanding and analyzing social and behavioral data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/Y45HV1N/intro-data-analysis" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Section 1: Getting Started Properly</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-basics-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is R, and why use it?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-r-vs-rstudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">R, RStudio, and how they relate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-files-and-environment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Scripts, RData, projects, environments, and R Markdown</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-projects-and-sessions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Working with R projects and R sessions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-objects-and-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Objects and functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-operations-and-packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Basic operations, custom functions, and packages</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-recap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Recap and getting data into R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Section 2: Manipulating and Visualizing Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-data-wrangling-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Data wrangling: basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-tidyverse-and-descriptives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Wrangling and describing data with the tidyverse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-data-visualization-principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">First principles of data visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-wrangling-for-psychology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Wrangling for psychology research</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-advanced-wrangling-optional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Advanced wrangling (optional)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Section 3: Statistical Modeling — Regressions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-data-and-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Data and the idea of a statistical model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-mean-as-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">The mean as a model: residuals, fit, and comparing models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-simple-linear-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">From the mean to the line: the simple linear model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-fitting-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Fitting and interpreting simple regression in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-multiple-and-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multiple regression and categorical predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-moderation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Moderation: when one predictor depends on another</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-bias-variance-assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Bias, variance, and the assumptions of the linear model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-diagnostics-and-limits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Diagnostics, model fit, and the limits of your model</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Section 4: Statistical Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-why-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Why inference? Samples, populations, and the standard error</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-pvalues-fisher-neyman-pearson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">P-values, Fisher, and Neyman-Pearson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-test-statistics-and-df.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">The inferential machinery: test statistics, z/t/F, and degrees of freedom</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-decisions-errors-power-sesoi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Decisions, errors, power, and SESOI</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-two-roles-multiple-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Two roles, multiple testing, and pre-registration</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#where-we-are" id="toc-where-we-are" class="nav-link active" data-scroll-target="#where-we-are"><span class="header-section-number">23.1</span> Where we are</a></li>
  <li><a href="#a-motivating-example-did-hannahs-bakery-shortchange-us" id="toc-a-motivating-example-did-hannahs-bakery-shortchange-us" class="nav-link" data-scroll-target="#a-motivating-example-did-hannahs-bakery-shortchange-us"><span class="header-section-number">23.2</span> A motivating example: did Hannah’s bakery shortchange us?</a></li>
  <li><a href="#the-test-statistic-distance-from-the-null-in-standard-error-units" id="toc-the-test-statistic-distance-from-the-null-in-standard-error-units" class="nav-link" data-scroll-target="#the-test-statistic-distance-from-the-null-in-standard-error-units"><span class="header-section-number">23.3</span> The test statistic: distance from the null, in standard-error units</a></li>
  <li><a href="#three-reference-distributions-z-t-f" id="toc-three-reference-distributions-z-t-f" class="nav-link" data-scroll-target="#three-reference-distributions-z-t-f"><span class="header-section-number">23.4</span> Three reference distributions: z, t, F</a>
  <ul class="collapse">
  <li><a href="#the-z-distribution-the-standard-normal" id="toc-the-z-distribution-the-standard-normal" class="nav-link" data-scroll-target="#the-z-distribution-the-standard-normal"><span class="header-section-number">23.4.1</span> The z distribution: the standard normal</a></li>
  <li><a href="#the-t-distribution-corrects-for-estimating-the-sd-from-the-sample" id="toc-the-t-distribution-corrects-for-estimating-the-sd-from-the-sample" class="nav-link" data-scroll-target="#the-t-distribution-corrects-for-estimating-the-sd-from-the-sample"><span class="header-section-number">23.4.2</span> The t distribution: corrects for estimating the SD from the sample</a></li>
  <li><a href="#the-f-distribution-a-ratio-of-two-variance-estimates" id="toc-the-f-distribution-a-ratio-of-two-variance-estimates" class="nav-link" data-scroll-target="#the-f-distribution-a-ratio-of-two-variance-estimates"><span class="header-section-number">23.4.3</span> The F distribution: a ratio of two variance estimates</a></li>
  <li><a href="#three-rulers-one-logic" id="toc-three-rulers-one-logic" class="nav-link" data-scroll-target="#three-rulers-one-logic"><span class="header-section-number">23.4.4</span> Three rulers, one logic</a></li>
  </ul></li>
  <li><a href="#degrees-of-freedom-the-information-budget" id="toc-degrees-of-freedom-the-information-budget" class="nav-link" data-scroll-target="#degrees-of-freedom-the-information-budget"><span class="header-section-number">23.5</span> Degrees of freedom: the information budget</a></li>
  <li><a href="#putting-it-all-together-what-r-is-doing-under-the-hood" id="toc-putting-it-all-together-what-r-is-doing-under-the-hood" class="nav-link" data-scroll-target="#putting-it-all-together-what-r-is-doing-under-the-hood"><span class="header-section-number">23.6</span> Putting it all together: what R is doing under the hood</a></li>
  <li><a href="#the-role-of-assumptions" id="toc-the-role-of-assumptions" class="nav-link" data-scroll-target="#the-role-of-assumptions"><span class="header-section-number">23.7</span> The role of assumptions</a></li>
  <li><a href="#looking-ahead" id="toc-looking-ahead" class="nav-link" data-scroll-target="#looking-ahead"><span class="header-section-number">23.8</span> Looking ahead</a></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding"><span class="header-section-number">23.9</span> Check your understanding</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">23.10</span> References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Y45HV1N/intro-data-analysis/edit/main/23-test-statistics-and-df.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/Y45HV1N/intro-data-analysis/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./21-why-inference.html">Section 4: Statistical Inference</a></li><li class="breadcrumb-item"><a href="./23-test-statistics-and-df.html"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">The inferential machinery: test statistics, z/t/F, and degrees of freedom</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">The inferential machinery: test statistics, z/t/F, and degrees of freedom</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="where-we-are" class="level2" data-number="23.1">
<h2 data-number="23.1" class="anchored" data-anchor-id="where-we-are"><span class="header-section-number">23.1</span> Where we are</h2>
<p>Chapter 21 introduced the sampling distribution and the standard error. Chapter 22 introduced the p-value and the two philosophies of testing (Fisher’s continuous evidence and Neyman-Pearson’s calibrated decision procedure). In both chapters we treated the sampling distribution as a known object whose shape we could appeal to: roughly normal for the mean, in particular.</p>
<p>This chapter fills in what we glossed over: how does R <em>actually</em> turn your sample data into a p-value? What is the universal mathematical machinery that lets the same software handle a mean, a regression slope, a difference between two groups, an ANOVA, and a chi-squared test? The answer involves three new ideas that work together:</p>
<ul>
<li>the <strong>test statistic</strong>, a way of converting raw sample values into a standardized “distance from the null,”</li>
<li>the <strong>z, t, and F distributions</strong>, which are the universal reference shapes the test statistic is compared against,</li>
<li><strong>degrees of freedom</strong>, the bookkeeping device that says how much information you have left after estimating things from the data.</li>
</ul>
<p>By the end of the chapter you will be able to read the “t value,” “Pr(&gt;|t|),” and the F-statistic at the bottom of <code>summary(lm(...))</code>. The mystery of the inferential machinery will turn out to be a smaller mystery than it first looks.</p>
</section>
<section id="a-motivating-example-did-hannahs-bakery-shortchange-us" class="level2" data-number="23.2">
<h2 data-number="23.2" class="anchored" data-anchor-id="a-motivating-example-did-hannahs-bakery-shortchange-us"><span class="header-section-number">23.2</span> A motivating example: did Hannah’s bakery shortchange us?</h2>
<p>We borrow a small story (used in many statistics textbooks, including Lakens 2022) to make the ideas concrete.</p>
<p>Imagine a bakery called Hannah’s that advertises 100-gram brownies. You are suspicious that Hannah’s brownies are systematically lighter than advertised. To check, you buy 25 brownies over a few weeks, weigh each one at home, and find an average of 95 grams across your 25 brownies. You also compute the sample standard deviation: 8 grams.</p>
<p>The question is essentially the same one that motivates every test in this book. Is 95 grams <em>suspicious</em> given that Hannah claims 100? Or is 95 a result we could easily get by chance because of sampling variability, even if Hannah’s true mean is really 100?</p>
<p>To answer this, we need three things:</p>
<ol type="1">
<li>A null hypothesis. We will entertain Hannah’s claim: H₀ says the population mean weight of Hannah’s brownies is exactly 100.</li>
<li>A statistic that summarizes the sample’s evidence against H₀.</li>
<li>A reference distribution that tells us how that statistic would behave across samples <em>if</em> H₀ were true.</li>
</ol>
<p>For the rest of the chapter we use this story to build up each piece of machinery in turn.</p>
</section>
<section id="the-test-statistic-distance-from-the-null-in-standard-error-units" class="level2" data-number="23.3">
<h2 data-number="23.3" class="anchored" data-anchor-id="the-test-statistic-distance-from-the-null-in-standard-error-units"><span class="header-section-number">23.3</span> The test statistic: distance from the null, in standard-error units</h2>
<p>Our sample mean is 95 g; the null value is 100 g; the difference is 5 g. That number alone is hard to interpret. Is 5 grams a lot or a little? It depends on how much sample means <em>typically</em> wobble across samples like ours, which is captured by the standard error.</p>
<p>The trick is to express the distance from the null <strong>in units of the standard error</strong>. That converts an unfamiliar 5-gram difference into a generic “this far from the null in standard-error units” measure that we can compare against a universal reference curve.</p>
<p>This standardized distance is the <strong>test statistic</strong>. For a one-sample mean, it takes the form:</p>
<p><span class="math display">\[
t = \frac{\bar{x} - \mu_0}{\text{SE}_{\bar{x}}}
\]</span></p>
<p>with the standard error estimated as <span class="math inline">\(\text{SE}_{\bar{x}} = s / \sqrt{n}\)</span> where <span class="math inline">\(s\)</span> is the sample SD. For Hannah’s brownies:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>x_bar <span class="ot">&lt;-</span> <span class="dv">95</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>mu0   <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>s     <span class="ot">&lt;-</span> <span class="dv">8</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>n     <span class="ot">&lt;-</span> <span class="dv">25</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>SE <span class="ot">&lt;-</span> s <span class="sc">/</span> <span class="fu">sqrt</span>(n)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>SE</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.6</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>t_stat <span class="ot">&lt;-</span> (x_bar <span class="sc">-</span> mu0) <span class="sc">/</span> SE</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>t_stat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -3.125</code></pre>
</div>
</div>
<p>So our sample mean is <span class="math inline">\(-3.125\)</span> standard errors away from the null value. The minus sign tells us we are on the “less than 100” side; the magnitude tells us we are three-and-a-bit SEs out from the null.</p>
<p>That is the key conceptual move. <strong>The test statistic is the standardized distance from the null.</strong> Once we have it, we can compare it to a universal reference curve that tells us how often a value of that size would occur by chance under H₀.</p>
<p>A few practical points about this move:</p>
<ul>
<li>Every classical statistical test follows the same template. Sample value → null value → standard error → standardized distance → reference distribution → p-value. The pattern repeats for means, slopes, group differences, correlations, variances. What changes is which specific formulas apply at each step.</li>
<li>The shape of the reference distribution depends on what we know about the data. If the population SD were known exactly, we would compare the test statistic to a standard normal curve (a <strong>z</strong> distribution). Because in practice we estimate the SD from the sample (we used <span class="math inline">\(s\)</span>, not a known <span class="math inline">\(\sigma\)</span>), the test statistic compares against a <strong>t</strong> distribution, whose shape depends on the sample size.</li>
</ul>
<p>We unpack these reference curves next.</p>
</section>
<section id="three-reference-distributions-z-t-f" class="level2" data-number="23.4">
<h2 data-number="23.4" class="anchored" data-anchor-id="three-reference-distributions-z-t-f"><span class="header-section-number">23.4</span> Three reference distributions: z, t, F</h2>
<p>The reference distribution is the known shape that the test statistic takes under H₀ given a particular set of assumptions. Three families appear most often.</p>
<section id="the-z-distribution-the-standard-normal" class="level3" data-number="23.4.1">
<h3 data-number="23.4.1" class="anchored" data-anchor-id="the-z-distribution-the-standard-normal"><span class="header-section-number">23.4.1</span> The z distribution: the standard normal</h3>
<p>The <strong>z distribution</strong> is the standard normal: mean 0, standard deviation 1. It is the reference curve when the test statistic is a sample mean (or anything that can be standardized into one) <strong>and</strong> the population SD is known exactly. In practice, the population SD is almost never known, so the pure z test is rarely used for one-sample problems. But the z distribution is what every other reference curve in this section converges to as sample sizes grow, so it is the natural starting point.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="23-test-statistics-and-df_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="624"></p>
</figure>
</div>
</div>
</div>
<p>The z distribution is symmetric and bell-shaped, with about 95% of its mass between <span class="math inline">\(-1.96\)</span> and <span class="math inline">\(1.96\)</span>. A z-statistic outside that range corresponds to a two-tailed p-value smaller than .05. The same 95% / .05 reference is what underlies the rule of thumb “results within roughly <span class="math inline">\(\pm 2\)</span> standard errors are unsurprising under H₀.”</p>
</section>
<section id="the-t-distribution-corrects-for-estimating-the-sd-from-the-sample" class="level3" data-number="23.4.2">
<h3 data-number="23.4.2" class="anchored" data-anchor-id="the-t-distribution-corrects-for-estimating-the-sd-from-the-sample"><span class="header-section-number">23.4.2</span> The t distribution: corrects for estimating the SD from the sample</h3>
<p>When we have to estimate the population SD from our sample (which is the realistic case), the test statistic does not quite follow a z distribution. Estimating the SD adds extra uncertainty: with small samples, the sample SD can be far from the true SD, and an extreme-looking test statistic might come from a sample whose SD estimate happened to be unusually small. The <strong>t distribution</strong> accounts for this by having heavier tails than the z. With a small sample, the t distribution says “be more cautious”: an apparently large test statistic might be less surprising than it would be under z.</p>
<p>The t distribution has a parameter called <strong>degrees of freedom (df)</strong>, which controls its shape. With small df the tails are fat; with large df the tails are thinner, and the t distribution converges to z. The intuition is that a larger sample gives a more reliable SD estimate, so the correction matters less.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="23-test-statistics-and-df_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="720"></p>
</figure>
</div>
</div>
</div>
<p>Notice how the three t curves (red, orange, blue) become indistinguishable from the dashed z line as df increases. At df = 30 the difference is already small; at df = 100 it would be invisible at this scale.</p>
<p>For our Hannah example, the t statistic was <span class="math inline">\(-3.125\)</span> with df = <span class="math inline">\(n - 1 = 24\)</span>. We can compute the corresponding two-tailed p-value directly:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="sc">-</span><span class="fl">3.125</span>, <span class="at">df =</span> <span class="dv">24</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.004602638</code></pre>
</div>
</div>
<p>About 0.0046, or roughly 0.5%. Under H₀ (Hannah’s claim of 100 g), results as extreme as ours (95 g or more extreme on either side) would occur less than half a percent of the time. The data are very surprising under H₀.</p>
</section>
<section id="the-f-distribution-a-ratio-of-two-variance-estimates" class="level3" data-number="23.4.3">
<h3 data-number="23.4.3" class="anchored" data-anchor-id="the-f-distribution-a-ratio-of-two-variance-estimates"><span class="header-section-number">23.4.3</span> The F distribution: a ratio of two variance estimates</h3>
<p>When we want to compare two variance estimates against each other (as in ANOVA or in the overall test of a regression model), the test statistic is no longer a standardized mean; it is a <em>ratio</em> of variances. Under H₀, the ratio of two variance estimates follows the <strong>F distribution</strong>. The F has <strong>two</strong> degrees-of-freedom parameters, one for the numerator and one for the denominator.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="23-test-statistics-and-df_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The F is right-skewed and runs from 0 to infinity (a ratio of squared things cannot be negative). The exact shape depends on the two df values. F appears in two main places in this book: the overall F-statistic at the bottom of <code>summary(lm(...))</code> (testing whether the model as a whole explains anything), and ANOVA (Chapter to come).</p>
</section>
<section id="three-rulers-one-logic" class="level3" data-number="23.4.4">
<h3 data-number="23.4.4" class="anchored" data-anchor-id="three-rulers-one-logic"><span class="header-section-number">23.4.4</span> Three rulers, one logic</h3>
<p>The big takeaway about z, t, and F is that they are three different <em>rulers</em> for three different kinds of standardized statistics, but the logic is the same: we compute a test statistic, look up its position on the universal reference curve, and read off a tail area (the p-value). The math is universal because mathematicians once computed each reference curve, and now we just look up the answer.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 30%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th>Situation</th>
<th>Test statistic</th>
<th>Reference distribution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One mean, population SD known</td>
<td><span class="math inline">\((\bar{x} - \mu_0) / (\sigma / \sqrt{n})\)</span></td>
<td>z</td>
</tr>
<tr class="even">
<td>One mean, population SD estimated</td>
<td><span class="math inline">\((\bar{x} - \mu_0) / (s / \sqrt{n})\)</span></td>
<td>t with df = n − 1</td>
</tr>
<tr class="odd">
<td>Two means, separate samples</td>
<td>difference of means / SE of the difference</td>
<td>t</td>
</tr>
<tr class="even">
<td>Slope in a simple regression</td>
<td>slope / SE of slope</td>
<td>t</td>
</tr>
<tr class="odd">
<td>Overall regression model</td>
<td>mean-square ratio</td>
<td>F</td>
</tr>
<tr class="even">
<td>Several group means (ANOVA)</td>
<td>mean-square ratio</td>
<td>F</td>
</tr>
</tbody>
</table>
<p>These are not separate tests; they are different specific cases of the same single logic.</p>
</section>
</section>
<section id="degrees-of-freedom-the-information-budget" class="level2" data-number="23.5">
<h2 data-number="23.5" class="anchored" data-anchor-id="degrees-of-freedom-the-information-budget"><span class="header-section-number">23.5</span> Degrees of freedom: the information budget</h2>
<p>The shape of the t (and F) distribution depends on degrees of freedom. We should be explicit about what df actually means, because most introductions present it as a magic formula and most students leave with no intuition for what it is.</p>
<p>The right way to think about it: <strong>degrees of freedom are an information budget</strong>. You start with n independent pieces of information (your n observations). Every time you estimate a parameter from the data, you spend one piece of that information. The df is what is left.</p>
<p>A small example. With Hannah’s 25 brownies, we started with 25 pieces of information. To compute the sample standard deviation, we first needed to compute the sample mean. That one calculation “spent” one piece of the information: once you know the mean, you only need 24 of the 25 deviations from the mean to determine the 25th (the deviations have to sum to zero). So the sample SD is computed using df = 25 - 1 = 24 effective pieces of information. That is why df for a one-sample t-test is n - 1.</p>
<p>The pattern generalizes. Each parameter estimated from the data costs one piece of information.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 35%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Test or model</th>
<th>df expended</th>
<th>df left</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One-sample t-test</td>
<td>1 (the mean)</td>
<td>n − 1</td>
</tr>
<tr class="even">
<td>Two-sample t-test</td>
<td>2 (two group means)</td>
<td>n − 2</td>
</tr>
<tr class="odd">
<td>Simple regression slope test</td>
<td>2 (intercept and slope)</td>
<td>n − 2</td>
</tr>
<tr class="even">
<td>Multiple regression with k predictors</td>
<td>k + 1 (intercept + k slopes)</td>
<td>n − k − 1</td>
</tr>
</tbody>
</table>
<p>This explains why df matters mechanically: a smaller df makes the t distribution heavier-tailed, which means a given test statistic produces a larger p-value. When you have few observations and have estimated several parameters, your estimates of the SE are unreliable, and the reference distribution should be more cautious. Df captures this exactly.</p>
<p>A concrete consequence: the same observed test statistic of, say, t = 2.5 corresponds to different p-values at different df.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="sc">-</span><span class="fl">2.5</span>, <span class="at">df =</span> <span class="dv">5</span>)   <span class="co"># df = 5</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0544901</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="sc">-</span><span class="fl">2.5</span>, <span class="at">df =</span> <span class="dv">30</span>)  <span class="co"># df = 30</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01811565</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="sc">-</span><span class="fl">2.5</span>, <span class="at">df =</span> <span class="dv">200</span>) <span class="co"># df = 200</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01322317</code></pre>
</div>
</div>
<p>With df = 5 the p-value is about 0.05; with df = 30 it is about 0.018; with df = 200 it is about 0.013. The same test statistic, but the conclusion depends on how reliable your SD estimate was. Larger df, more reliable estimate, smaller p-value.</p>
</section>
<section id="putting-it-all-together-what-r-is-doing-under-the-hood" class="level2" data-number="23.6">
<h2 data-number="23.6" class="anchored" data-anchor-id="putting-it-all-together-what-r-is-doing-under-the-hood"><span class="header-section-number">23.6</span> Putting it all together: what R is doing under the hood</h2>
<p>You will rarely compute a test statistic by hand. R has built-in functions for every standard test:</p>
<ul>
<li><code>t.test()</code> for one- and two-sample t-tests.</li>
<li><code>cor.test()</code> for correlations.</li>
<li><code>chisq.test()</code> for chi-squared tests.</li>
<li><code>aov()</code> for ANOVA.</li>
<li><code>summary(lm(...))</code> reports t-statistics and an overall F.</li>
</ul>
<p>When R reports a p-value, it has done the following in order:</p>
<ol type="1">
<li>Computed the appropriate test statistic from your data: the standardized distance from the null.</li>
<li>Identified the correct reference distribution and its df from the design.</li>
<li>Looked up the tail area beyond your test statistic on the reference distribution.</li>
<li>Reported that tail area as the p-value.</li>
</ol>
<p>For Hannah’s brownies, the t-test would look like this in R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate 25 brownies with mean 95, SD 8 to recreate the example</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">7</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>brownies <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">25</span>, <span class="at">mean =</span> <span class="dv">95</span>, <span class="at">sd =</span> <span class="dv">8</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(brownies, <span class="at">mu =</span> <span class="dv">100</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  brownies
t = -0.67498, df = 24, p-value = 0.5061
alternative hypothesis: true mean is not equal to 100
95 percent confidence interval:
  94.77481 102.64977
sample estimates:
mean of x 
 98.71229 </code></pre>
</div>
</div>
<p>The output reports the t-statistic, the df, and the two-tailed p-value, exactly as we computed them by hand. The 95% confidence interval is a different (related) inferential output we will not develop here.</p>
<p>The most important thing this whole chapter does for you, in practice, is the following. Look back at the <code>summary(lm(...))</code> output from Chapter 16:</p>
<pre><code>Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)   4.1962    0.2827   14.843  &lt; 2e-16
hours_weekly  0.0816    0.0271    3.016   0.00313

Residual standard error: 1.556 on 118 degrees of freedom
F-statistic: 9.1 on 1 and 118 DF, p-value: 0.003133</code></pre>
<p>You now know what every column means.</p>
<ul>
<li><strong>Estimate</strong> is the parameter value (intercept or slope), as in Section 3.</li>
<li><strong>Std. Error</strong> is the estimated standard deviation of the sampling distribution of that parameter (Chapter 21).</li>
<li><strong>t value</strong> is the test statistic: Estimate / Std. Error, i.e., the standardized distance from the null value of zero. For <code>hours_weekly</code>: 0.0816 / 0.0271 ≈ 3.016.</li>
<li><strong>Pr(&gt;|t|)</strong> is the p-value, computed by looking up the t-statistic on a t-distribution with 118 df (the n − 2 from the simple regression).</li>
<li><strong>F-statistic and its p-value</strong> at the bottom test the model as a whole: is at least one slope different from zero? In simple regression with one predictor, this is exactly the same test as the t-test on the slope (and gives the same p-value, .003).</li>
<li><strong>Residual standard error</strong> is the typical size of the residuals; 118 df because we estimated 2 parameters (intercept and slope) from the n = 120 observations.</li>
</ul>
<p>Everything you politely ignored in Chapter 16 is now interpretable.</p>
</section>
<section id="the-role-of-assumptions" class="level2" data-number="23.7">
<h2 data-number="23.7" class="anchored" data-anchor-id="the-role-of-assumptions"><span class="header-section-number">23.7</span> The role of assumptions</h2>
<p>The reference distributions (z, t, F) deliver correct p-values <em>only when</em> the assumptions of the test are reasonable. We have already seen most of these assumptions in Chapter 19, but they show up again here because they are what makes the inferential machinery work.</p>
<p>For a one-sample t-test, the assumptions are essentially:</p>
<ul>
<li><strong>Independence.</strong> Observations are independent of each other (no clustering, no repeated measures from the same person).</li>
<li><strong>Random sampling.</strong> The sample is drawn at random from the population we want to make claims about.</li>
<li><strong>Approximate normality of the data, or large enough n that the CLT applies.</strong> The sampling distribution of the mean is approximately normal under one of these conditions.</li>
</ul>
<p>For a regression, the LINE assumptions from Chapter 19 (Linearity, Independence, Normality of residuals, Equal variance) play the same role.</p>
<p>When assumptions are violated, the reference distribution is no longer guaranteed to match the actual sampling distribution of the test statistic. R will still print a p-value; the p-value just may not mean what we want it to mean. Lakens (2022, Chapter 1) emphasizes this point repeatedly: a p-value is part of a <em>calibrated procedure</em>, and the calibration requires the assumptions to hold.</p>
</section>
<section id="looking-ahead" class="level2" data-number="23.8">
<h2 data-number="23.8" class="anchored" data-anchor-id="looking-ahead"><span class="header-section-number">23.8</span> Looking ahead</h2>
<p>You can now read every column of standard regression output, t-test output, and ANOVA output. You can also explain what R is computing when it returns a p-value, and you can answer the question “what changes when df changes.”</p>
<p>Chapter 24 turns from the <em>computation</em> of p-values to the <em>decision-theoretic structure</em> that surrounds them. What happens when the procedure is wrong? What is the trade-off between Type I and Type II errors? What does it mean to “have 80% power,” and why is that claim meaningless without an anchor like SESOI (the Smallest Effect Size of Interest)?</p>
<p>Chapter 25 then returns to the philosophical issues raised at the end of Chapter 22: the distinction between exploratory and confirmatory work, the multiple-testing problem, the practical discipline of pre-registration, and the famous Ioannidis observation that under realistic conditions a large fraction of published “significant” findings may be false.</p>
</section>
<section id="check-your-understanding" class="level2" data-number="23.9">
<h2 data-number="23.9" class="anchored" data-anchor-id="check-your-understanding"><span class="header-section-number">23.9</span> Check your understanding</h2>
<p><strong>1. What is a “test statistic”?</strong></p>
<div id="radio_UXIUVHMOIB" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_UXIUVHMOIB" value=""> <span>It is the average of the sample minus the null value, expressed in the original units of measurement and reported directly without further transformation.</span></label><label><input type="radio" autocomplete="off" name="radio_UXIUVHMOIB" value="answer"> <span>It is the standardized distance from the null hypothesis: the difference between the sample value and the null, divided by the standard error of the sample value.</span></label><label><input type="radio" autocomplete="off" name="radio_UXIUVHMOIB" value=""> <span>It is the probability that the null hypothesis is true given the observed sample, computed using the reference distribution and the sample size.</span></label><label><input type="radio" autocomplete="off" name="radio_UXIUVHMOIB" value=""> <span>It is the difference between two consecutive sample means computed across replications of the study under identical conditions.</span></label>
</div>
<p><strong>2. In a one-sample t-test of the mean, what is the denominator of the test statistic?</strong></p>
<div id="radio_LUHZXJNZHP" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_LUHZXJNZHP" value=""> <span>It is the difference in sample size between two competing experimental groups divided by the smaller group's standard deviation as estimated from the pilot study.</span></label><label><input type="radio" autocomplete="off" name="radio_LUHZXJNZHP" value=""> <span>It is the residual standard error of a linear regression model divided by the square root of the F-statistic for the same regression coefficient.</span></label><label><input type="radio" autocomplete="off" name="radio_LUHZXJNZHP" value=""> <span>It is the sample variance divided by the population variance, used when one of the two is known and the other has to be estimated from the dataset.</span></label><label><input type="radio" autocomplete="off" name="radio_LUHZXJNZHP" value="answer"> <span>It is the standard error of the sample mean, equal to the sample standard deviation divided by the square root of the sample size, used when the population SD is estimated from the sample.</span></label>
</div>
<p><strong>3. What is “degrees of freedom” (df)?</strong></p>
<div id="radio_RWEFCUIPWH" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_RWEFCUIPWH" value=""> <span>It is the difference between the z and the t distributions caused by sample size effects on the dispersion of the sampling distribution under H0.</span></label><label><input type="radio" autocomplete="off" name="radio_RWEFCUIPWH" value="answer"> <span>It is a parameter of the t (and F) distribution that controls its shape; intuitively, it is the amount of independent information left in the sample after estimating parameters from the data.</span></label><label><input type="radio" autocomplete="off" name="radio_RWEFCUIPWH" value=""> <span>It is the number of statistical tests run by the researcher across all the analyses performed on the dataset, including supplementary and follow-up analyses.</span></label><label><input type="radio" autocomplete="off" name="radio_RWEFCUIPWH" value=""> <span>It is the difference between observed and predicted values in a regression model, used in the formula for the residual standard error and the model R-squared.</span></label>
</div>
<p><strong>4. When does each of the z, t, and F reference distributions apply?</strong></p>
<div id="radio_PRRHFJMXGY" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_PRRHFJMXGY" value=""> <span>The z distribution applies when the data are normal, the t distribution applies when the data are non-normal, and the F distribution applies when the data are heavily skewed.</span></label><label><input type="radio" autocomplete="off" name="radio_PRRHFJMXGY" value=""> <span>The z distribution applies when the sample size is large, the t distribution applies when it is small, and the F distribution applies when there is a single categorical predictor with two levels.</span></label><label><input type="radio" autocomplete="off" name="radio_PRRHFJMXGY" value="answer"> <span>The z distribution applies when the population SD is known, the t distribution applies when the SD is estimated from the sample (its shape depending on df), and the F distribution applies to ratios of variance estimates such as in ANOVA or the overall regression test.</span></label><label><input type="radio" autocomplete="off" name="radio_PRRHFJMXGY" value=""> <span>The z, t, and F distributions are interchangeable when the sample size is at least 30; the choice depends only on whether the test is two-tailed or one-tailed and on the convention of the software package.</span></label>
</div>
<p><strong>5. How does the t distribution differ from the z distribution, and why?</strong></p>
<div id="radio_YXVLFDPQKM" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_YXVLFDPQKM" value=""> <span>The t distribution has lighter tails than the z, meaning extreme test statistics are less likely under the t and produce smaller p-values for any given test statistic at moderate df.</span></label><label><input type="radio" autocomplete="off" name="radio_YXVLFDPQKM" value="answer"> <span>The t distribution has heavier tails than the z at small df; an extreme test statistic is therefore less surprising under the t than under the z, and yields a larger p-value at small df; as df grows the t converges to the z.</span></label><label><input type="radio" autocomplete="off" name="radio_YXVLFDPQKM" value=""> <span>The t and z are identical at all values of df; the apparent difference seen in textbook figures is a visual artifact of how the curves are drawn on the standardized scale.</span></label><label><input type="radio" autocomplete="off" name="radio_YXVLFDPQKM" value=""> <span>The z always has wider tails than the t, regardless of df, because the z accounts for additional uncertainty introduced by sampling whereas the t assumes the variance is fixed.</span></label>
</div>
<p><strong>6. In <code>summary(lm(...))</code> output, what do the “Std. Error,” “t value,” and “Pr(&gt;|t|)” columns represent for a coefficient?</strong></p>
<div id="radio_LWWRAQALKP" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_LWWRAQALKP" value=""> <span>The Pr(&gt;|t|) column reports the probability that the slope is exactly zero in the population given the observed data, calculated by Bayesian inversion of the t-statistic on the t reference distribution.</span></label><label><input type="radio" autocomplete="off" name="radio_LWWRAQALKP" value=""> <span>The t value column is the standardized residual of the prediction made by the regression model for the participant whose observed value deviates most from the model's predicted value.</span></label><label><input type="radio" autocomplete="off" name="radio_LWWRAQALKP" value=""> <span>The Std. Error column is the residual standard error of the regression model around the fitted line, identical for every coefficient and equal to the square root of the model's mean squared residual.</span></label><label><input type="radio" autocomplete="off" name="radio_LWWRAQALKP" value="answer"> <span>The t value is the coefficient divided by its Std. Error, the standardized distance from the null of zero; the Pr(&gt;|t|) is the two-tailed p-value computed by looking up |t value| on a t distribution with the residual degrees of freedom (n − k − 1).</span></label>
</div>
<p><strong>7. Why does the same observed |t| = 2.5 give a smaller p-value at df = 200 than at df = 5?</strong></p>
<div id="radio_BIZQHIIVTN" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_BIZQHIIVTN" value=""> <span>At df = 5 the p-value is larger because the procedure has less power to detect a real effect; the difference is purely about power and not about the shape of the reference distribution.</span></label><label><input type="radio" autocomplete="off" name="radio_BIZQHIIVTN" value=""> <span>At df = 200 the p-value is larger because the t distribution at high df becomes wider in the tails, making any given test statistic relatively less surprising than at small df.</span></label><label><input type="radio" autocomplete="off" name="radio_BIZQHIIVTN" value=""> <span>The p-values are essentially equal because the t and z distributions converge in the tails, regardless of the value of df chosen for the comparison procedure.</span></label><label><input type="radio" autocomplete="off" name="radio_BIZQHIIVTN" value="answer"> <span>At df = 5 the t distribution has heavier tails, so a |t| of 2.5 is more likely under H0 than at df = 200; the same test statistic therefore yields a larger p-value at df = 5 (about 0.05) than at df = 200 (about 0.01).</span></label>
</div>
<p><strong>8. In what sense is the F distribution a “ratio” distribution?</strong></p>
<div id="radio_KXTVXHYRCR" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_KXTVXHYRCR" value=""> <span>An F distribution describes the sampling distribution of a single regression coefficient under the null that the population value of that coefficient is exactly zero across all replications.</span></label><label><input type="radio" autocomplete="off" name="radio_KXTVXHYRCR" value=""> <span>An F distribution describes the sampling distribution of the residuals of a fitted regression model around the OLS line, accounting for the model's degrees of freedom.</span></label><label><input type="radio" autocomplete="off" name="radio_KXTVXHYRCR" value="answer"> <span>An F distribution describes the sampling distribution of a ratio of two variance estimates under the null; it is right-skewed and is parameterized by two df values (numerator and denominator).</span></label><label><input type="radio" autocomplete="off" name="radio_KXTVXHYRCR" value=""> <span>An F distribution describes the joint sampling distribution of all the residuals in a multilevel model and is used to derive standard errors for the random-effect variance components.</span></label>
</div>
<p><strong>9. Why do the assumptions of a test matter for the validity of its p-value?</strong></p>
<div id="radio_MRUKWBTBRH" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_MRUKWBTBRH" value=""> <span>Assumptions are administrative paperwork required by some journals, with no real effect on the validity of the p-value computed by the software.</span></label><label><input type="radio" autocomplete="off" name="radio_MRUKWBTBRH" value="answer"> <span>The reference distributions z, t, F are derived under specific assumptions; when those assumptions are violated, the reference distribution may not match the actual sampling distribution of the test statistic, and the reported p-value may not mean what the formula says it means.</span></label><label><input type="radio" autocomplete="off" name="radio_MRUKWBTBRH" value=""> <span>Assumptions matter only for small samples; for samples of any reasonable size, the law of large numbers makes the p-value valid regardless of how the data were collected.</span></label><label><input type="radio" autocomplete="off" name="radio_MRUKWBTBRH" value=""> <span>Assumptions are only relevant for Bayesian inference; in frequentist hypothesis testing the test statistic and the reference distribution are robust to any kind of assumption violation.</span></label>
</div>
<p><strong>10. What is the “information budget” view of degrees of freedom?</strong></p>
<div id="radio_EQUPIOVKHK" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_EQUPIOVKHK" value=""> <span>Each parameter estimated from the data adds to the available pool of information, so the model with more predictors always has more df left over for inference about each parameter.</span></label><label><input type="radio" autocomplete="off" name="radio_EQUPIOVKHK" value="answer"> <span>Each parameter estimated from the data spends one piece of the original independent information; df is what is left, controls the shape of the reference distribution, and shrinks as more parameters are estimated.</span></label><label><input type="radio" autocomplete="off" name="radio_EQUPIOVKHK" value=""> <span>Df is fixed at n - 1 for any analysis that uses the sample mean, regardless of how many additional parameters such as slopes or interaction terms are estimated by the model.</span></label><label><input type="radio" autocomplete="off" name="radio_EQUPIOVKHK" value=""> <span>Df is the same as the standard error in modern statistical software, and reporting one of the two is sufficient when describing the precision of a coefficient in a research paper.</span></label>
</div>
</section>
<section id="references" class="level2" data-number="23.10">
<h2 data-number="23.10" class="anchored" data-anchor-id="references"><span class="header-section-number">23.10</span> References</h2>
<p>Lakens, D. (2022). <em>Improving your statistical inferences</em>. Chapter 1, “Using p-values to test a hypothesis.” <a href="https://lakens.github.io/statistical_inferences/01-pvalue.html" class="uri">https://lakens.github.io/statistical_inferences/01-pvalue.html</a></p>
<p>Navarro, D. J. (2018). <em>Learning statistics with R: A tutorial for psychology students and other beginners</em> (Version 0.6), Chapter 13 (“Comparing two means”). <a href="https://learningstatisticswithr.com" class="uri">https://learningstatisticswithr.com</a></p>


</section>

</main> <!-- /main -->
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./22-pvalues-fisher-neyman-pearson.html" class="pagination-link" aria-label="P-values, Fisher, and Neyman-Pearson">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">P-values, Fisher, and Neyman-Pearson</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./24-decisions-errors-power-sesoi.html" class="pagination-link" aria-label="Decisions, errors, power, and SESOI">
        <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Decisions, errors, power, and SESOI</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Y45HV1N/intro-data-analysis/edit/main/23-test-statistics-and-df.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/Y45HV1N/intro-data-analysis/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>