project:
  type: book
  output-dir: _book
  resources:
    - data/
book:
  title: Understanding and analyzing social and behavioral data
  author: Yashvin Seetahul
  date: today
  search: true
  repo-url: https://github.com/Y45HV1N/intro-data-analysis
  repo-actions:
  - edit
  - issue
  page-navigation: true
  chapters:
  - index.qmd
  - part: 'Section 1: Getting Started Properly'
    chapters:
    - 01-basics-r.qmd
    - 02-r-vs-rstudio.qmd
    - 03-files-and-environment.qmd
    - 04-projects-and-sessions.qmd
    - 05-objects-and-functions.qmd
    - 06-operations-and-packages.qmd
    - 07-recap.qmd
  - part: 'Section 2: Manipulating and Visualizing Data'
    chapters:
    - 08-data-wrangling-basics.qmd
    - 09-tidyverse-and-descriptives.qmd
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 3
    number-sections: true
    code-copy: true
    code-overflow: wrap
    css:
      - include/webex.css
      - include/custom.css
    include-after-body: include/webex.js
execute:
  freeze: auto
  echo: true
  warning: false
  message: false
